name: CI/CD to GitOps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
         install: true
         driver-opts: network=host

      - name: Build Docker image
        run: docker buildx build --load -t ${{ secrets.DOCKER_USERNAME }}/flask-backend:latest .

      - name: Debug Buildx
        run: docker buildx ls

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-backend:latest

      - name: Clone GitOps repo
        run: |
          git clone https://github.com/zizo1112/flask-gitops-demo.git
          cd flask-gitops-demo
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          sed -i 's|image: .*|image: '${{ secrets.DOCKER_USERNAME }}'/flask-backend:latest|' apps/flask-app/deployment.yaml
          git add .
          git commit -m "Update image to latest"
          git push https://${{ secrets.GITOPS_TOKEN }}@github.com/zizo1112/flask-gitops-demo.git
